# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

1. Faça um CÓDIGO que mostre a mensagem "Olá ETE PORTO DIGITAL!" na tela.
"""

mensagem = "Olá ETE PORTO DIGITAL!"
print(mensagem)

"""2. Faça um CÓDIGO que peça um número e então mostre a mensagem O número informado foi [número]."""

numero = input("Informe um número: ")
print("O número informado foi", numero)

"""3. Faça um CÓDIGO que peça dois números e imprima a soma."""

numero1 = float(input("Digite o primeiro número: "))
numero2 = float(input("Digite o segundo número: "))

soma = numero1 + numero2

print("A soma dos dois números é:", soma)

"""4. Faça um CÓDIGO que peça as 4 notas bimestrais e mostre a média final."""

nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a segunda nota: "))
nota3 = float(input("Digite a terceira nota: "))
nota4 = float(input("Digite a quarta nota: "))

media = (nota1 + nota2 + nota3 + nota4) / 4

print("A média final é:", media)

"""5. Faça um CÓDIGO que converta metros para centímetros."""

metros = float(input("Digite o valor em metros: "))

centimetros = metros * 100

print("O valor em centímetros é:", centimetros)

"""6. Faça um CÓDIGO que peça o raio de um círculo, calcule e mostre sua área."""

import math

raio = float(input("Digite o raio do círculo: "))

area = math.pi * raio**2

print("A área do círculo é:", area)

"""7. Faça um CÓDIGO que calcule a área de um quadrado, em seguida mostre o dobro desta área para o usuário."""

lado = float(input("Digite o valor do lado do quadrado: "))

area = lado ** 2
dobro_area = 2 * area

print("A área do quadrado é:", area)
print("O dobro da área é:", dobro_area)

"""8. Faça um CÓDIGO que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês."""

valor_por_hora = float(input("Digite o valor do seu salário por hora: "))
horas_trabalhadas = float(input("Digite o número de horas trabalhadas no mês: "))

salario_mensal = valor_por_hora * horas_trabalhadas

print("Seu salário mensal é:", salario_mensal)

"""9. Faça um CÓDIGO que peça um valor e mostre na tela se o valor é positivo ou negativo."""

valor = float(input("Digite um valor: "))

if valor > 0:
    print("O valor é positivo.")
elif valor < 0:
    print("O valor é negativo.")
else:
    print("O valor é zero.")

"""10. Faça um CÓDIGO que verifique se uma letra digitada é "F" ou "M". Conforme a letra escrever: F - Feminino, M - Masculino, Sexo Inválido."""

letra = input("Digite uma letra: ")

if letra == "F" or letra == "f":
    print("F - Feminino")
elif letra == "M" or letra == "m":
    print("M - Masculino")
else:
    print("Sexo Inválido")